#!/usr/bin/env python
from gui.application import Application
from gui import Gtk

# Initialize application
Application()

# Make CTRL+C work in GTK
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

# Run GTK main loop
Gtk.main()
